apiVersion: apps/v1
kind: Deployment
metadata: 
  name: story-server
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: story
  template: 
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: berkakipek96/kube-data-demo:3.0
          env:
            - name: STORY_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: folder
          resources:
            requests:
              memory: 256Mi
              cpu: 500m
            limits:
              memory: 512Mi
              cpu: "1"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes: 
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc